apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netanchor
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - gateway.yaml
  - httproute.yaml
images:
  - name: ghcr.io/fox27374/netanchor
    newTag: 1.4.2
